commits for step 6
Daniel-J-94/Back_End_Portfolio_Project_DJ pull request #2
Opened 2023-03-28 10:03 UTC by Daniel-J-94

2023-03-28 11:10 UTC, itskatherine requested changes
Hi Daniel, a strong start but few things to look at, once you've had a look over these comments and added the tests could you please resubmit this PR 🙂

2023-03-28 11:10 UTC, itskatherine commented on __tests__/app.test.js
> +      .get(`/api/reviews/five/comments`)
This test should be a 400, as its an invalid datatype for the id rather than a valid but non-existant datatype (like an id of 100000)

2023-03-28 11:10 UTC, itskatherine commented on controllers/getCommentsByReviewIdController.js
> +      res.status(200).send(result);
Best practise is to send back out responses on an appropriate key, so I'd expect an object returned on the key of `comments`, (so `send({comments: result})`)
Can you change this (it will mean you'll need to update your tests)

2023-03-28 11:10 UTC, itskatherine commented on models/getCommentsByReviewIdModel.js
> +exports.getterCommentsByReviewId = (revIdFromReq) => {
Can you name the model something a bit more distinct from the controller than `getter` for example `fetchCommentsByReviewId`

2023-03-28 11:10 UTC, itskatherine commented on models/getCommentsByReviewIdModel.js
> +  console.log(
Remember to get rid of console logs for PRs 👀

2023-03-28 11:10 UTC, itskatherine commented on controllers/getCommentsByReviewIdController.js
> +  const revIdFromReq = req.params;
It would be best to take the `review_id` off the `req.params` at this point rather than in the model, either by destructuring it or just accessing `req.params.review_id`

2023-03-28 11:10 UTC, itskatherine commented on __tests__/app.test.js
> +});
Missing a couple of tests here: need to check
404: valid but non-existant `article_id`
200: Returns an empty comments array when given an article_id where article exists but has no comments

2023-03-28 11:10 UTC, itskatherine commented on __tests__/app.test.js
> +        const body = resultResponse.body;
Remember to check the length of the array before your forEach loop, as an empty array would skip the forEach loop, skipping all the expect statements within and potentially giving you a false positive

2023-03-30 09:35 UTC, Harrison365 commented
Looks good to go ✅ 
Well done, Daniel!

2023-03-30 10:48 UTC, merged